-- MySQL Script generated by MySQL Workbench
-- Mo 15 Jan 2018 18:46:16 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjectZero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjectZero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectZero` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ProjectZero` ;

-- -----------------------------------------------------
-- Table `ProjectZero`.`Benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Benutzer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `passwort` VARCHAR(32) NOT NULL,
  `geburtsdatum` DATE NULL,
  `email` VARCHAR(255) NOT NULL,
  `geheimfrage` VARCHAR(255) NULL,
  `geheimantwort` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Gruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Gruppe` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `beschreibung` VARCHAR(255) NOT NULL,
  `offen` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Notiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Notiz` (
  `id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `titel` VARCHAR(32) NOT NULL,
  `text` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Notiz_Benutzer1_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Notiz_Benutzer`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Termin` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `titel` VARCHAR(32) NOT NULL,
  `beschreibung` TEXT NULL,
  `start` DATETIME NOT NULL,
  `ende` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Termin_1_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Termin_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Forum_Oberthema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Forum_Oberthema` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gruppe_id` INT(10) UNSIGNED NOT NULL,
  `titel` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Forum_Oberthema_1_idx` (`gruppe_id` ASC),
  CONSTRAINT `fk_Forum_Oberthema_1`
    FOREIGN KEY (`gruppe_id`)
    REFERENCES `ProjectZero`.`Gruppe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Gruppen_Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Gruppen_Chat` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gruppe_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Gruppen_Chat_1_idx` (`gruppe_id` ASC),
  CONSTRAINT `fk_Gruppen_Chat_1`
    FOREIGN KEY (`gruppe_id`)
    REFERENCES `ProjectZero`.`Gruppe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Publisher` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Genre` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Spiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Spiel` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `beschreibung` LONGTEXT NOT NULL,
  `publisher_id` INT(10) UNSIGNED NOT NULL,
  `genre_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Spiel_Publisher1_idx` (`publisher_id` ASC),
  INDEX `fk_Spiel_Genre1_idx` (`genre_id` ASC),
  CONSTRAINT `fk_Spiel_Publisher`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `ProjectZero`.`Publisher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spiel_Genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `ProjectZero`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Benutzer_Spiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Benutzer_Spiel` (
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `spiel_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`benutzer_id`, `spiel_id`),
  INDEX `fk_Bibliothek_Spiel_idx` (`spiel_id` ASC),
  CONSTRAINT `fk_Bibliothek_Benutzer`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bibliothek_Spiel`
    FOREIGN KEY (`spiel_id`)
    REFERENCES `ProjectZero`.`Spiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Bewertung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Bewertung` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `spiel_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `titel` VARCHAR(45) NOT NULL,
  `text` MEDIUMTEXT NULL,
  `bewertung` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bewertung_2_idx` (`spiel_id` ASC),
  INDEX `fk_Bewertung_1_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Bewertung_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bewertung_2`
    FOREIGN KEY (`spiel_id`)
    REFERENCES `ProjectZero`.`Spiel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Freundesliste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Freundesliste` (
  `benutzer_id1` INT(10) UNSIGNED NOT NULL,
  `benutzer_id2` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`benutzer_id1`, `benutzer_id2`),
  INDEX `fk_Freundesliste_2_idx` (`benutzer_id2` ASC),
  CONSTRAINT `fk_Freundesliste_1`
    FOREIGN KEY (`benutzer_id1`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Freundesliste_2`
    FOREIGN KEY (`benutzer_id2`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Freund_Anfrage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Freund_Anfrage` (
  `von_benutzer_id` INT(10) UNSIGNED NOT NULL,
  `zu_benutzer_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`von_benutzer_id`, `zu_benutzer_id`),
  INDEX `fk_Freund_Anfrage_2_idx` (`zu_benutzer_id` ASC),
  CONSTRAINT `fk_Freund_Anfrage_1`
    FOREIGN KEY (`von_benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Freund_Anfrage_2`
    FOREIGN KEY (`zu_benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Privat_Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Privat_Chat` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Gruppenchat_Nachricht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Gruppenchat_Nachricht` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gruppenchat_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gruppenchat_Nachricht_2_idx` (`gruppenchat_id` ASC),
  INDEX `fk_Gruppenchat_Nachricht_1_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Gruppenchat_Nachricht_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gruppenchat_Nachricht_2`
    FOREIGN KEY (`gruppenchat_id`)
    REFERENCES `ProjectZero`.`Gruppen_Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Vote` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `vote` TINYINT(1) NULL,
  `benutzer_id` INT(10) UNSIGNED NULL,
  `bewertung_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vote_1_idx` (`benutzer_id` ASC),
  INDEX `fk_Vote_2_idx` (`bewertung_id` ASC),
  CONSTRAINT `fk_Vote_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_2`
    FOREIGN KEY (`bewertung_id`)
    REFERENCES `ProjectZero`.`Bewertung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Notiz_Teilnehmer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Notiz_Teilnehmer` (
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `notiz_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`benutzer_id`, `notiz_id`),
  INDEX `fk_Notiz_Teilnehmer_2_idx` (`notiz_id` ASC),
  CONSTRAINT `fk_Notiz_Teilnehmer_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notiz_Teilnehmer_2`
    FOREIGN KEY (`notiz_id`)
    REFERENCES `ProjectZero`.`Notiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Termin_Teilnehmer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Termin_Teilnehmer` (
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `termin_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`benutzer_id`, `termin_id`),
  INDEX `fk_Termin_Teilnehmer_2_idx` (`termin_id` ASC),
  CONSTRAINT `fk_Termin_Teilnehmer_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Termin_Teilnehmer_2`
    FOREIGN KEY (`termin_id`)
    REFERENCES `ProjectZero`.`Termin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Chat_Nachricht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Chat_Nachricht` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chat_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Chat_Nachricht_1_idx` (`chat_id` ASC),
  INDEX `fk_Chat_Nachricht_2_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Chat_Nachricht_1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `ProjectZero`.`Privat_Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_Nachricht_2`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Chat_Benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Chat_Benutzer` (
  `chat_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`chat_id`, `benutzer_id`),
  INDEX `fk_Chat_Benutzer_2_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Chat_Benutzer_1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `ProjectZero`.`Privat_Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_Benutzer_2`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Offener_Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Offener_Chat` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `passwort` VARCHAR(32) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Gruppe_Benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Gruppe_Benutzer` (
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `gruppe_id` INT(10) UNSIGNED NOT NULL,
  `rolle` VARCHAR(32) NULL,
  PRIMARY KEY (`benutzer_id`, `gruppe_id`),
  INDEX `fk_Gruppe_Benutzer_2_idx` (`gruppe_id` ASC),
  CONSTRAINT `fk_Gruppe_Benutzer_1`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gruppe_Benutzer_2`
    FOREIGN KEY (`gruppe_id`)
    REFERENCES `ProjectZero`.`Gruppe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Offener_Chat_Nachricht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Offener_Chat_Nachricht` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chat_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Privat_Chat_Nachricht_2_idx` (`benutzer_id` ASC),
  INDEX `fk_Privat_Chat_Nachricht_1_idx` (`chat_id` ASC),
  CONSTRAINT `fk_Offener_Chat_Nachricht_1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `ProjectZero`.`Offener_Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offener_Chat_Nachricht_2`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Offener_Chat_Benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Offener_Chat_Benutzer` (
  `chat_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_Privat_Chat_Benutzer_1_idx` (`chat_id` ASC),
  INDEX `fk_Offener_Chat_Benutzer_2_idx` (`benutzer_id` ASC),
  PRIMARY KEY (`chat_id`, `benutzer_id`),
  CONSTRAINT `fk_Offener_Chat_Benutzer_1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `ProjectZero`.`Offener_Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offener_Chat_Benutzer_2`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Forum_Unterthema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Forum_Unterthema` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `oberthema_id` INT(10) UNSIGNED NOT NULL,
  `titel` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Forum_Unterthema_1_idx` (`oberthema_id` ASC),
  CONSTRAINT `fk_Forum_Unterthema_1`
    FOREIGN KEY (`oberthema_id`)
    REFERENCES `ProjectZero`.`Forum_Oberthema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectZero`.`Forum_Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectZero`.`Forum_Post` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `thema_id` INT(10) UNSIGNED NOT NULL,
  `benutzer_id` INT(10) UNSIGNED NOT NULL,
  `text` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Forum_Post_1_idx` (`thema_id` ASC),
  INDEX `fk_Forum_Post_2_idx` (`benutzer_id` ASC),
  CONSTRAINT `fk_Forum_Post_1`
    FOREIGN KEY (`thema_id`)
    REFERENCES `ProjectZero`.`Forum_Unterthema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Forum_Post_2`
    FOREIGN KEY (`benutzer_id`)
    REFERENCES `ProjectZero`.`Benutzer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
